### ISSUE TITLE
Handling of more selectors than html and root

### ISSUE THREAD

**Issue by AlexisCharp** [csstools/postcss-color-mod-function#42]
First of all, thanks for this plugin as it works very well.

However, I had a problem when I modified the selector in which the custom-properties are declared.
I moved from
`:root {...}` to `:root, ::backdrop {...}`

Then it stopped working because the plugin is searching for a `/^:root$/i` selector.

Is there any particular reason for restricting the use of root alone ?

**Comment by AlexisCharp** [comment]
Also, as this plugin appears to not be maintained anymore, do you have replacement ideas ? Couldn't find something similar :(

**Comment by Antonio-Laguna** [comment]
@AlexisCharp as you noticed this plugin is no longer maintained since the spec died. The closest one would be [@csstools/postcss-relative-color-syntax](https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-relative-color-syntax#readme) for which we wrote [an article](https://preset-env.cssdb.org/blog/postcss-relative-color-syntax/) not so long ago!

Hope that's helpful
